# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-25 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwaretest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='softwaretest',
            options={'verbose_name': 'ISTQB(软件测试)术语表', 'verbose_name_plural': 'ISTQB(软件测试)术语表'},
        ),
        migrations.AlterField(
            model_name='softwaretest',
            name='short',
            field=models.CharField(blank=True, default='-', max_length=10, null=True, verbose_name='英文缩写'),
        ),
    ]
