# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-26 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwaretest', '0002_auto_20180225_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwaretest',
            name='long_EN',
            field=models.CharField(max_length=50, unique=True, verbose_name='英文全称'),
        ),
    ]
