# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-25 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxdevinfo',
            name='accesstoken',
            field=models.CharField(default=11232, max_length=256, verbose_name='ACCESSTOKEN'),
            preserve_default=False,
        ),
    ]
