# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 20:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlClassify',
            fields=[
                ('type_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='url分类编码')),
                ('type_name', models.CharField(max_length=40, unique=True, verbose_name='url分类名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'URL分类管理',
                'verbose_name_plural': 'URL分类管理',
            },
        ),
        migrations.CreateModel(
            name='UrlManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=100, unique=True, verbose_name='URL名称')),
                ('url_link', models.URLField(unique=True, verbose_name='URL地址')),
                ('note', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('classify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favurls.UrlClassify', verbose_name='分类')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'URL管理',
                'verbose_name_plural': 'URL管理',
            },
        ),
    ]
