# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 21:32
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo', verbose_name='头像')),
                ('peer', models.CharField(max_length=100, verbose_name='职业')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮箱')),
                ('summary', ckeditor.fields.RichTextField(max_length=2000, verbose_name='简介')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lastupdate', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '关于我',
                'verbose_name_plural': '关于我',
            },
        ),
        migrations.CreateModel(
            name='Declare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(max_length=2000, verbose_name='申明内容')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lastupdate', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('wechar', models.ImageField(blank=True, null=True, upload_to='wechar', verbose_name='微信收款码')),
                ('zifubao', models.ImageField(blank=True, null=True, upload_to='zhifubao', verbose_name='支付宝收款码')),
            ],
            options={
                'verbose_name': '申明',
                'verbose_name_plural': '申明',
            },
        ),
        migrations.CreateModel(
            name='PMPDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_EN', models.CharField(max_length=50, unique=True, verbose_name='英文全称')),
                ('long_CN', models.CharField(max_length=50, verbose_name='中文全称')),
                ('short', models.CharField(default='-', max_length=10, verbose_name='英文缩写')),
                ('description', models.TextField(max_length=1000, verbose_name='术语解释')),
                ('version', models.CharField(blank=True, default='第六版', max_length=15, null=True, verbose_name='PMBOK版本')),
            ],
            options={
                'verbose_name': 'PMP术语',
                'verbose_name_plural': 'PMP术语',
            },
        ),
    ]
