# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-25 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmp', '0002_auto_20180225_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmpdescription',
            name='short',
            field=models.CharField(default='-', max_length=10, verbose_name='英文缩写'),
        ),
    ]
